Repository SOPT-32-CDS/BaeMin-iOS, pull requests merged in 2023-05, with the labels that each got.

#10 [Setting]: #9 목데이터구조추가
  BeaMin-iOS/BeaMin-iOS.xcodeproj/project.pbxproj
  BeaMin-iOS/BeaMin-iOS/Data/Home/Home.swift
  BeaMin-iOS/BeaMin-iOS/Data/OrderDetail/OrderDetail.swift
  BeaMin-iOS/BeaMin-iOS/Data/OrderMain/StoreDetail.swift
Labels: Done, 🦁 의성

#12 [Feat]: #11 주문하기상세 페이지 구현
  BeaMin-iOS/BeaMin-iOS.xcodeproj/project.pbxproj
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Color/seperateGray.colorset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/popularityMark.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/popularityMark.imageset/popularityMark.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/popularityMark.imageset/popularityMark@2x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/popularityMark.imageset/popularityMark@3x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/MenuImage.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/MenuImage.imageset/MenuImage.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/MenuImage.imageset/MenuImage@2x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/MenuImage.imageset/MenuImage@3x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/checkBoxFalse.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/checkBoxFalse.imageset/checkBoxFalse.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/checkBoxTrue.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/checkBoxTrue.imageset/checkBoxTrue.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/minus.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/minus.imageset/minus.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/plus.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/OrderDetail/plus.imageset/plus.png
  BeaMin-iOS/BeaMin-iOS/App/SceneDelegate.swift
  BeaMin-iOS/BeaMin-iOS/Data/OrderDetail/OrderDetail.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/View/OrederMainView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/ViewController/OrderDetailViewController.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/Cell/AddMenuTableViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/Component/BMBasicButton.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/Component/BMNavigationBar.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/Component/CheckBox.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/Component/ChoiceChipView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/Component/MenuStepperView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/Component/SeperateView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/OrderDetailFooterViewView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/OrderDetailHeaderView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/OrderDetailSectionHeaderView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/PriceInfoView.swift
  BeaMin-iOS/BeaMin-iOS/TestViewController.swift
  BeaMin-iOS/CustomExtension/Constant/Constant.swift
  BeaMin-iOS/CustomExtension/Extenstions/Int+.swift
  BeaMin-iOS/DesignSystem/Palette/Palette.swift
Labels: 🦁 의성, Feat

#16 [Feat] #15 CustomTabBar 구현
  BeaMin-iOS/BeaMin-iOS.xcodeproj/project.pbxproj
  BeaMin-iOS/BeaMin-iOS/App/SceneDelegate.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/CustomTabBar/CustomTabBarItem.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/CustomTabBar/CustomTabBarView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/ViewController/HomViewController.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/ViewController/HomeViewController.swift
  BeaMin-iOS/CustomExtension/Extenstions/UIButton+.swift
Labels: Done, 🐰 아라

#27 [Fix] #26 긴급 오류 해결
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Views/Cell/CartStoreMenuTableViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Views/Component/DeliveryInfoView.swift
Labels: Done, 🐰 아라

#37 [Feat] #36 CartAPI(Get, Delete) 구현
  BeaMin-iOS/BeaMin-iOS.xcodeproj/project.pbxproj
  BeaMin-iOS/BeaMin-iOS/App/SceneDelegate.swift
  BeaMin-iOS/BeaMin-iOS/Data/Cart/CartModel.swift
  BeaMin-iOS/BeaMin-iOS/Data/Cart/CartModelDTO.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Manager/CartManager.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/ViewController/CartViewController.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Views/CartInfoView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Views/Cell/CartStoreMenuTableViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Views/Component/DeliveryInfoView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Views/Component/DeliveryPriceInfoView.swift
  BeaMin-iOS/CustomExtension/Constant/Constant.swift
  BeaMin-iOS/CustomExtension/Enum/NetworkResult.swift
Labels: 🦁 의성, Feat

#39 [Feat] #38 주문완료 view 및 api호출
  BeaMin-iOS/BeaMin-iOS.xcodeproj/project.pbxproj
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/OrderCompleteImage.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/OrderCompleteImage.imageset/OrderCompleteImage.png
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Manager/CartManager.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/ViewController/CartViewController.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/ViewController/OrderCompleteViewController.swift
  BeaMin-iOS/CustomExtension/Constant/Constant.swift
Labels: Design, 🦁 의성, Feat

#40 [Feat] #28 메인 화면 Layout 구현
  BeaMin-iOS/BeaMin-iOS.xcodeproj/project.pbxproj
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Color/chipBorderGreen.colorset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/img_advertise.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/img_advertise.imageset/img.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/img_advertise.imageset/img@2x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/img_advertise.imageset/img@3x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/mainCoupon.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/mainCoupon.imageset/Property 1=Frame 7928.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/mainCoupon.imageset/Property 1=Frame 7928@2x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/mainCoupon.imageset/Property 1=Frame 7928@3x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/mainNowCoupon.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/mainNowCoupon.imageset/Property 1=Variant2.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/mainNowCoupon.imageset/Property 1=Variant2@2x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/mainNowCoupon.imageset/Property 1=Variant2@3x.png
  BeaMin-iOS/BeaMin-iOS/App/SceneDelegate.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/Component/HomeAdvertiseCollectionViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/Component/HomeChipCollectionViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/Component/HomeStoreSmallCollectionViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/HomeView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/MainNavigationView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/SectionFooterView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/SectionHeaderView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/ViewController/HomeViewController.swift
  BeaMin-iOS/CustomExtension/Constant/Constant.swift
  BeaMin-iOS/DesignSystem/Palette/Palette.swift
Labels: Done, 🐰 아라

#48 [Feat] #47 이미지캐싱 사용하는방법, 클디서 task구현완료
  BeaMin-iOS/BeaMin-iOS.xcodeproj/project.pbxproj
  BeaMin-iOS/BeaMin-iOS/Data/Cart/CartModelDTO.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Manager/CartManager.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/ViewController/CartViewController.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/ViewController/OrderCompleteViewController.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Views/CartStoreMenuSectionHeaderView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Cart/Views/Cell/CartStoreMenuTableViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Manager/OrderDetailManager.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/ViewController/OrderDetailViewController.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/Cell/AddMenuTableViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/Component/BMBasicButton.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderDetail/Views/View/PriceInfoView.swift
  BeaMin-iOS/CustomExtension/Extenstions/UIImageView+.swift
Labels: 🦁 의성, Feat

#49 [Fix] #46 메인 화면 Layout 수정
  BeaMin-iOS/BeaMin-iOS.xcodeproj/project.pbxproj
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/img_test.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/img_test.imageset/Rectangle 6667438.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/img_test.imageset/Rectangle 6667438@2x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/img_test.imageset/Rectangle 6667438@3x.png
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/Component/HomeChipCollectionViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/Component/HomeStoreBigCollectionViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/View/Component/HomeStoreSmallCollectionViewCell.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/ViewController/HomeViewController.swift
  BeaMin-iOS/CustomExtension/Constant/Constant.swift
Labels: Fix, 🐰 아라

#42 [Feat] #34 Section HeaderView 구현
  BeaMin-iOS/BeaMin-iOS.xcodeproj/project.pbxproj
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/ic_rightarrow.imageset/Contents.json
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/ic_rightarrow.imageset/ic_rightarrow.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/ic_rightarrow.imageset/ic_rightarrow@2x.png
  BeaMin-iOS/BeaMin-iOS/App/Assets.xcassets/Image/ic_rightarrow.imageset/ic_rightarrow@3x.png
  BeaMin-iOS/BeaMin-iOS/Data/OrderMain/StoreDetail.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderMain/View/OrderMainCartButton.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderMain/View/OrderMainView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderMain/View/PopularMenuSectionHeaderView.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/OrderMain/ViewController/OrderMainViewController.swift
  BeaMin-iOS/CustomExtension/Constant/Constant.swift
Labels: 🦖 유진, Feat

#51 ✅완성✅
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/Manager/HomeManager.swift
  BeaMin-iOS/BeaMin-iOS/Presenter/Home/ViewController/HomeViewController.swift
Labels: Done, 🐰 아라, 🦁 의성, 🦖 유진
